 name: music_player
description: A simple offline music player app

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  on_audio_query: ^2.9.0
  just_audio: ^0.9.38
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
